### ISSUE TITLE
Join force ?

### ISSUE THREAD

**Issue by Lctrs** [robertfausk/mink-panther-driver#1]
Funny things. Looks like we had the same idea at the same time.

https://github.com/Lctrs/mink-panther-driver

I don't think it's worth it that 2 differents libs coexists for such a trivial thing. So wanna join force ?

**Comment by robertfausk** [comment]
Yeah. Good idea.
I‘ve suggested MinkPantherDriver as an official driver (@stof @aik099).
Let‘s wait for their answer:)

Atm our solutions still have some issues:
My implementation currently lacks of unmerged PRs in symfony/panther.
Your implementation is based on unsupported unofficial minkphp/driver-testsuite branch which is not compatible with all others mink driver in the wild.
